feat: add general style file
N1kk1337/rs-clone pull request #18
Opened 2023-02-02 13:45 UTC by KarinaBertosh

2023-02-02 19:22 UTC, N1kk1337 requested changes

2023-02-02 19:22 UTC, N1kk1337 commented on src/general.scss
> +// если надо ещё меньше то 12px
Так может тоже в переменные тогда?

2023-02-03 13:53 UTC, N1kk1337 approved these changes

2023-02-03 13:53 UTC, N1kk1337 approved these changes

2023-02-03 17:29 UTC, Baxromxoja16 approved these changes

2023-02-03 17:39 UTC, merged