Modal register
N1kk1337/rs-clone pull request #24
Opened 2023-02-03 17:46 UTC by Baxromxoja16

Добавлен модальный вход и регистрация. Импортируете их и используете

2023-02-05 16:27 UTC, KarinaBertosh approved these changes

2023-02-05 18:18 UTC, N1kk1337 requested changes
1) Кажется эта ветка создана от очень старого состояние ветки develop, пока конфликтов нет, но лучше иногда проверять актуальность
2) Тут есть валидация на корректность ввода, но, насколько я понял, непосредственно проверки юзера и пароля при логине нет. Я думаю их стоит сделать уже на этом этапе используя тестовые данные. Когда появится реальный бэк - менять придётся не очень много.

2023-02-05 18:19 UTC, N1kk1337 commented on src/components/LoginModal/LoginModal.tsx
> +  console.log(password);
Перед созданием пулреквеста лучше удалить тестовые выводы в консоль. По идее линтер должен выводить это как ошибку.

2023-02-06 07:50 UTC, Baxromxoja16 commented on src/components/LoginModal/LoginModal.tsx
> +  console.log(password);
Я убираю консоль, когда приходит бэк. иначе выдает ошибку, что пароль нигде не вызывается

2023-02-07 18:55 UTC, N1kk1337 approved these changes
Всё отлично, код понятный.

2023-02-07 18:57 UTC, merged